### ISSUE TITLE
Native support in strace with --seccomp-bpf

### ISSUE THREAD

**Issue by pchaigno** [shinh/strace#1]
Hi! :wave: 

Strace now supports this natively, with the (experimental) `--seccomp-bpf` option, in the 5.3 version.

**Comment by pchaigno** [comment]
@shinh Did you get a chance to look into this? Should I add a note to the README?

**Comment by shinh** [comment]
Finally! It's a very good news. Sure, I've updated the README.md of this repo to explicitly declare this is an obsolete experiment.

**Comment by shinh** [comment]
Thanks for both your work and notifying the news!

**Comment by pchaigno** [comment]
You're welcome! If you have any idea for improvement, do share. I'm still looking to improve this :-)
